#!/usr/bin/env python3
"""Regenerate the derived artifacts for a DGRefHelp pathway version.

Source of truth (edit these by hand):
  html/page-contents.html        -- Background / intro; renders at top of page
  html/accordion-sections.json   -- [{"heading", "html"}, ...] in display order

Generated from them (do not edit by hand):
  html/NN-<slug>.html            -- one ready-to-paste file per accordion box
  PASTE-GUIDE.md                 -- maps each Umbraco RTE box to its file
  outputs/cms-upload-bundle.json -- combined structured bundle

Standard accordion headings (the default template) are listed in
STANDARD_HEADINGS. Sections outside that set are allowed and treated as
pathway-specific -- they are still emitted, and flagged in the run summary and
the paste guide so the deviation is visible.

Usage:
  python3 scripts/emit-sections.py pathways/<topic>/<version>/ [more versions...]
"""
import json
import re
import sys
from pathlib import Path

# The default accordion template. Order here is the preferred display order.
STANDARD_HEADINGS = [
    "Assessment",
    "Primary care management",
    "Who to refer",
    "Who not to refer",
    "References",
]


def slug(heading: str) -> str:
    s = heading.lower().replace("&", "and")
    return re.sub(r"[^a-z0-9]+", "-", s).strip("-")


def is_standard(heading: str) -> bool:
    return heading.strip().lower() in {h.lower() for h in STANDARD_HEADINGS}


def repo_relative(path: Path) -> str:
    parts = path.resolve().parts
    if "pathways" in parts:
        i = parts.index("pathways")
        return "/".join(parts[i:])
    return str(path)


def process(version_dir: Path) -> None:
    html_dir = version_dir / "html"
    sections_path = html_dir / "accordion-sections.json"
    page_path = html_dir / "page-contents.html"
    if not sections_path.exists():
        sys.exit(f"error: {sections_path} not found")

    sections = json.loads(sections_path.read_text())
    page_html = page_path.read_text() if page_path.exists() else ""

    # Remove stale generated per-section files (NN-*.html) before re-emitting.
    for old in html_dir.glob("[0-9][0-9]-*.html"):
        old.unlink()

    emitted = []
    for i, sec in enumerate(sections, 1):
        heading = sec["heading"]
        fn = f"{i:02d}-{slug(heading)}.html"
        (html_dir / fn).write_text(sec["html"] + "\n")
        emitted.append((heading, fn, is_standard(heading)))

    _write_paste_guide(version_dir, emitted)
    _write_bundle(version_dir, sections, page_html)
    _print_summary(version_dir, emitted)


def _write_paste_guide(version_dir: Path, emitted) -> None:
    lines = [
        "# Umbraco paste guide",
        "",
        "Generated by `scripts/emit-sections.py` -- do not edit by hand.",
        "",
        "Each file below is raw HTML for one Umbraco RTE box. Paste via the code",
        "view (`<>`), not the visual editor, so the callout-box styling is preserved.",
        "",
        "## Page contents (top of page)",
        "",
        "- Paste `html/page-contents.html` into the **Page contents** RTE box.",
        "",
        "## Accordion sections (in order)",
        "",
        "Set each accordion **heading** and paste the matching file into its RTE code view:",
        "",
        "| # | Accordion heading | Paste this file | |",
        "|---|---|---|---|",
    ]
    for i, (heading, fn, standard) in enumerate(emitted, 1):
        tag = "" if standard else "pathway-specific"
        lines.append(f"| {i} | {heading} | `html/{fn}` | {tag} |")
    lines += [
        "",
        "Standard headings: " + ", ".join(STANDARD_HEADINGS) + ".",
        "Anything marked *pathway-specific* is outside the default template.",
        "",
    ]
    (version_dir / "PASTE-GUIDE.md").write_text("\n".join(lines))


def _write_bundle(version_dir: Path, sections, page_html: str) -> None:
    outputs = version_dir / "outputs"
    outputs.mkdir(exist_ok=True)
    bundle_path = outputs / "cms-upload-bundle.json"

    # Preserve a human-set topic if one exists; otherwise derive from the folder.
    topic = None
    if bundle_path.exists():
        try:
            topic = json.loads(bundle_path.read_text()).get("topic")
        except (json.JSONDecodeError, OSError):
            topic = None
    if not topic:
        topic = version_dir.parent.name.replace("-", " ")

    base_rel = repo_relative(version_dir)
    bundle = {
        "topic": topic,
        "page_contents_html": page_html,
        "accordion_sections": sections,
        "artifact_paths": {
            "page_contents_html": f"{base_rel}/html/page-contents.html",
            "accordion_sections_json": f"{base_rel}/html/accordion-sections.json",
            "cms_upload_bundle_json": f"{base_rel}/outputs/cms-upload-bundle.json",
        },
    }
    bundle_path.write_text(json.dumps(bundle, ensure_ascii=False, indent=2) + "\n")


def _print_summary(version_dir: Path, emitted) -> None:
    print(f"{repo_relative(version_dir)}:")
    present = {h.strip().lower() for h, _, _ in emitted}
    for heading, fn, standard in emitted:
        mark = " " if standard else "*"
        print(f"  [{mark}] {fn}  <- {heading}")
    missing = [h for h in STANDARD_HEADINGS if h.lower() not in present]
    if missing:
        print("  missing standard sections: " + ", ".join(missing))
    print("  (* = pathway-specific, outside the default template)")


def main(argv) -> None:
    if not argv:
        sys.exit(__doc__)
    for arg in argv:
        process(Path(arg))


if __name__ == "__main__":
    main(sys.argv[1:])
